

const lang = {
    en : {
        search: "Search",
        GPTSearchPlaceholder: "What would you like to watch today?",
        home: "Home",
        welcome: "Welcome",
        logout: "Logout",
        signIn: "Sign In",
        emailAddress: "Email Address",
        password: "Password",
        newToNetflix: "New to Netflix?",
        signUpNow: "Sign up now",
        signUp: "Sign Up",
        fullName: "Full Name",
        alreadyRegistered: "Already registered?",
    },

    hi: {
        search: "खोजें",
        GPTSearchPlaceholder: "आप आज क्या देखना चाहेंगे?",
        home: "होम",
        welcome: "स्वागत हैं",
        logout: "लोग आउट",
        signIn: "साइन इन करें",
        emailAddress: "ईमेल पता",
        password: "पासवर्ड",
        newToNetflix: "नेटफ्लिक्स पर नए हैं?",
        signUpNow: "अभी साइन अप करें",
        signUp: "साइन अप करें",
        fullName: "पूरा नाम",
        alreadyRegistered: "पहले से पंजीकृत है?",
    },
    tel: {
        search: "వెతకండి",
        GPTSearchPlaceholder: "మీరు ఈ రోజు ఏమి చూడాలి?",
        home: "హోమ్",
        welcome: "స్వాగతం",
        logout: "లాగ్ అవుట్",
        signIn: "సైన్ ఇన్ చేయండి",
        emailAddress: "ఇమెయిల్ చిరునామా",
        password: "పాస్వర్డ్",
        newToNetflix: "నెట్‌ఫ్లిక్స్‌కు కొత్తగా?",
        signUpNow: "ఇప్పుడే సైన్ అప్ చేయండి",
        signUp: "సైన్ అప్ చేయండి",
        fullName: "పూర్తి పేరు",
        alreadyRegistered: "ఇప్పటికే నమోదైనదా?",
    },
    tam: {
        search: "தேடு",
        GPTSearchPlaceholder: "நீங்கள் இன்று என்னைப் பார்க்க விரும்புகிறீர்களா?",
        home: "ஹோம்",
        welcome: "வரவேற்கின்றோம்",
        logout: "வெளியேறு",
        signIn: "உள்நுழைய",
        emailAddress: "மின்னஞ்சல் முகவரி",
        password: "கடவுச்சொல்",
        newToNetflix: "நெட்ஃபிளிக்ஸில் புதியவரா?",
        signUpNow: "இப்போது பதிவு செய்க",
        signUp: "பதிவு செய்ய",
        fullName: "முழு பெயர்",
        alreadyRegistered: "ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது?",
    }
};

export default lang;